name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt update
        sudo apt -y install build-essential libgtk-4 libvte-2.91-0

    - name: make build
      run: make build

    #- name: make test
    #  run: make test
