name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: |
        sudo apt update
        sudo apt -y install build-essential git ninja-build libgnutls28-dev meson pkg-config libgtk-4-dev
        git clone https://gitlab.gnome.org/GNOME/vte
        cd vte
        meson _build -gtk3=false -gtk4=true
        ninja -C _build
        sudo ninja -C _build install
        sudo ldconfig

    - name: make build
      run: make build

    #- name: make test
    #  run: make test
